// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCEgWWfm4yktWqlEXy01f-jXq1ywYJhQU',
    appId: '1:480572814025:web:7919678290653ded0ad318',
    messagingSenderId: '480572814025',
    projectId: 'bellybutton-6b338',
    authDomain: 'bellybutton-6b338.firebaseapp.com',
    databaseURL: 'https://bellybutton-6b338-default-rtdb.firebaseio.com',
    storageBucket: 'bellybutton-6b338.firebasestorage.app',
    measurementId: 'G-3D6D8XLC3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1kCnC9kySf30deoq4V74KmMV4eIpWNiI',
    appId: '1:480572814025:android:3f40859d108c7fe50ad318',
    messagingSenderId: '480572814025',
    projectId: 'bellybutton-6b338',
    databaseURL: 'https://bellybutton-6b338-default-rtdb.firebaseio.com',
    storageBucket: 'bellybutton-6b338.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu3-DBw89GE9hZ93Gw7yj6_AqFdhPOfwQ',
    appId: '1:480572814025:ios:53464a1ba2b1cf0c0ad318',
    messagingSenderId: '480572814025',
    projectId: 'bellybutton-6b338',
    databaseURL: 'https://bellybutton-6b338-default-rtdb.firebaseio.com',
    storageBucket: 'bellybutton-6b338.firebasestorage.app',
    iosBundleId: 'com.bellybutton.dev.bellybutton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu3-DBw89GE9hZ93Gw7yj6_AqFdhPOfwQ',
    appId: '1:480572814025:ios:53464a1ba2b1cf0c0ad318',
    messagingSenderId: '480572814025',
    projectId: 'bellybutton-6b338',
    databaseURL: 'https://bellybutton-6b338-default-rtdb.firebaseio.com',
    storageBucket: 'bellybutton-6b338.firebasestorage.app',
    iosBundleId: 'com.bellybutton.dev.bellybutton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCEgWWfm4yktWqlEXy01f-jXq1ywYJhQU',
    appId: '1:480572814025:web:261d798952572c520ad318',
    messagingSenderId: '480572814025',
    projectId: 'bellybutton-6b338',
    authDomain: 'bellybutton-6b338.firebaseapp.com',
    databaseURL: 'https://bellybutton-6b338-default-rtdb.firebaseio.com',
    storageBucket: 'bellybutton-6b338.firebasestorage.app',
    measurementId: 'G-ELC0CGWM7Z',
  );
}
